generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Post
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          post
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Post Managment
      filter:  ~
      form:    ~
      edit:    
         title: Editing Post "%%id%%"
      new:     ~
