generator:
  class: sfDoctrineGenerator
  param:
    model_class:           User
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: User Managment
        display: [id, name, surname, username, email, created_at, updated_at]
      filter:  ~
      form:    ~
      edit:    
         title: Editing User "%%name%%"
      new:     ~
